version: '3.9'
services:
  3d_pcr:
    restart: always
    build: .
    container_name: '3d_pcr'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./notebooks:/root/notebooks
      - ./data:/root/data
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --NotebookApp.token=''